name = "ConvolutionalFactorizations"
uuid = "2f15623e-e53f-4337-8528-f301fa2431ee"
authors = ["degleris1 <degleris1@gmail.com>"]
version = "0.1.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MLJModelInterface = "e80e1ace-859a-464e-9ed9-23947d8ae3ea"
